name: Release Workload

on:
  workflow_dispatch:
    inputs:
      net_sdk_version:
        description: 'Target .NET SDK Version to Release'
        required: true
      release_manifest:
        description: 'Release workload packs?'
        type: boolean
        required: false
        default: false
      release_reference:
        description: 'Release Samsung.Tizen.Ref pack?'
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Wix toolset
      run: sudo apt-get install -y wixl

    - name: Build
      env:
        PRERELEASE_TAG: "stable"
      run: make install -d DOTNET_VERSION=${{ github.event.inputs.net_sdk_version }}
      working-directory: ./workload
      continue-on-error: true

    - name: Push Manifest/SDK/Runtime packs
      if: ${{ github.event.inputs.release_manifest == true }}
      run: |
        echo "Pushing Manifest packs for version ${{ github.event.inputs.net_sdk_version }}"...
        dotnet nuget push ./workload/out/nuget-unsigned/Samsung.NET.Sdk.Tizen.Manifest.*.nupkg \
                      -k ${{ secrets.NUGET_APIKEY }} \
                      -s https://api.nuget.org/v3/index.json \
                      -t 3000
                      --skip-duplicate
        dotnet nuget push ./workload/out/nuget-unsigned/Samsung.Tizen.Sdk.*.nupkg \
                      -k ${{ secrets.NUGET_APIKEY }} \
                      -s https://api.nuget.org/v3/index.json \
                      -t 3000
                      --skip-duplicate
        dotnet nuget push ./workload/out/nuget-unsigned/Samsung.NETCore.App.Runtime.*.nupkg \
                      -k ${{ secrets.NUGET_APIKEY }} \
                      -s https://api.nuget.org/v3/index.json \
                      -t 3000
                      --skip-duplicate
        dotnet nuget push ./workload/out/nuget-unsigned/Samsung.Tizen.Templates.*.nupkg \
                      -k ${{ secrets.NUGET_APIKEY }} \
                      -s https://api.nuget.org/v3/index.json \
                      -t 3000
                      --skip-duplicate

    - name: Push Ref pack
      if: ${{ github.event.inputs.release_reference == true }}
      run: |
        echo "Pushing Manifest packs for version ${{ github.event.inputs.net_sdk_version }}"...
        dotnet nuget push ./workload/out/nuget-unsigned/Samsung.Tizen.Ref.*.nupkg \
                      -k ${{ secrets.NUGET_APIKEY }} \
                      -s https://api.nuget.org/v3/index.json \
                      -t 3000
                      --skip-duplicate
